/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    docs: [
        'intro'
    ],
    geonode: [
        'gis/geonode',
        'gis/geonode/install-basic',
        'gis/geonode/install-advanced',
    ],
    windows: [
        'os/windows',
        'os/windows/wsl',
    ],
    geoportal: [
        'projects/geoportal',
        {
            type: 'category', label: 'Getting Started', collapsed: false, items: [
                'projects/geoportal/installation',
                'projects/geoportal/configuration',
                'projects/geoportal/folder-structure',
            ]
        },
        {
            type: 'category', label: 'Support', items: [
                'projects/geoportal/troubleshooting',
                'projects/geoportal/faq',
            ]
        },

    ]

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
     */
};
